#!/bin/bash

while read -r _ _ _ node state status; do
	[[ "$state" == "floating" ]] && [[ "$status" == "on" ]] && bspc config -n $node border_width 0
#	[[ "$state" == "floating" ]] && [[ "$status" == "off" ]] && bspc config -n $node border_width 2
done < <(bspc subscribe node_state) &


while read -r _ _ _ node; do
    lastFocus=$(bspc query -N -n focused.tiled)
    [[ "$node" ==  $lastFocus ]] && echo "yeet" && bspc config -n $node border_width 2
done < <(bspc subscribe node_focus)

