#!/bin/sh

### Bspwm Config ###

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.

# Workspaces
bspc monitor DP-2 -d 1 2
bspc monitor HDMI-0 -d 3 4 5

# Window Settings

# ~/.bin/wm.bspwm_dual_borders & 

bspc config border_width 	  0
bspc config window_gap      7

. "${HOME}/.cache/wal/colors.sh"

# Colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_modifier mod1

bspc config focus_follows_pointer true
bspc config pointer_motion_interval 6.94

### Window Rules ###

bspc rule -a "Zoom Group Chat" state=floating
bspc rule -a "rofi" state=floating
bspc rule -a "NVIDIA X Server Settings" state=floating
bspc rule -a "ksysguard" state=floating
#bspc rule -a "ckb-next" desktop=5
bspc rule -a "pulseeffects" desktop=^5
bspc rule -a "discord" desktop=2 state=floating
bspc rule -a "keepassxc" desktop=5
bspc rule -a Zathura state=tiled

bsp-layout set tall 6 -- --master-size 0.4

### Autostart Apps ###

# Key Daemon
sxhkd -c ~/.config/bspwm/sxhkdrc & 

# Polybar
~/.config/polybar/launch.sh &

~/Scripts/bspwm/floating_desktop &
~/Scripts/bspwm/floating_desktop2 &


# Power Manager
# xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
#feh --bg-scale ~/Pictures/wallpapers/imaginarysliceoflife/yuumei-wenqing-yan-better-tomorrow-by-yuumei-daa3fwv_x2.png


wal -R
# feh --bg-scale ~/Pictures/gallery-dl/pixiv/User/27383311_夕凪/尾道暮情_0.jpg

# Enables Windows Key
ksuperkey &
#ckb-next &
~/.config/dunst/launchdunst.sh
pulseeffects &
ulseeffects &
discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy &
keepassxc &
XDG_CURRENT_DESKTOP="KDE" chromium &


# Compositor
picom --experimental-backends --backend glx &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &

# Load Bitmap Fonts
xset +fp ~/.local/share/fonts &
xset fp rehash &
xset fp+ /usr/share/fonts/bitmap &

# Keyboard & Mouse Settings
xset r rate 190 60
xset m 0 0

# Enable Alt+Tab
sleep 5; alttab -fg "#c5c8c6" -bg "#1d1f21" -frame "#c5c8c6" -t 300x150 -i 299x64 -font "xft:SF Pro Text-12" &

setxkbmap us
tmux &

killall borders
# ~/.config/bspwm/borders &

sshfs -o kernel_cache,allow_other,auto_cache,reconnect,no_readahead endorsi@163.172.221.42:/media/Endorsi /media/Endorsi

rclone mount maiBase:/ ~/Mai/

sudo ntpd -u ntp:ntp
